"""empty message

Revision ID: 729e06c20be7
Revises: ae6c4424ace8
Create Date: 2023-10-16 14:14:14.063690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '729e06c20be7'
down_revision = 'ae6c4424ace8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('object', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('message', sa.String(length=450), nullable=False))
        batch_op.drop_column('is_active')
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_column('message')
        batch_op.drop_column('object')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
