"""empty message

Revision ID: 84360daa9e1d
Revises: 729e06c20be7
Create Date: 2023-10-20 16:06:38.679461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84360daa9e1d'
down_revision = '729e06c20be7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.String(length=9), nullable=True))
        batch_op.add_column(sa.Column('date', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('country', sa.String(length=80), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('country')
        batch_op.drop_column('date')
        batch_op.drop_column('phone_number')

    # ### end Alembic commands ###
